# Generated by Django 3.1.3 on 2022-07-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20220715_0344'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='films',
            field=models.ManyToManyField(to='film.Film'),
        ),
    ]
